Upgrade to 3.0.1-SNAPSHOT
Enedis-OSS/chutney pull request #15
Opened 2024-11-25 17:22 UTC by nbrouand

2024-11-26 07:52 UTC, DelaunayAlex requested changes

2024-11-26 07:52 UTC, DelaunayAlex commented on pom.xml
> +    <tag>3.0.1-SNAPSHOT</tag>
Usually we keep HEAD during development, did the maven command do that ?

2024-11-27 08:56 UTC, boddissattva approved these changes

2024-11-27 08:57 UTC, DelaunayAlex approved these changes

2024-11-27 13:26 UTC, KarimGl approved these changes

2024-11-27 16:00 UTC, merged