feat(server): global search in scenario, campaign and dataset
Enedis-OSS/chutney pull request #46
Opened 2024-12-24 14:59 UTC by KarimGl

#### Issue Number
fixes #

#### Describe the changes you've made

- One shot index scenario, campaign and dataset at startup.
- Add global search bar to search in scenario, campaign and dataset.

![Screenshot 2024-12-24 at 15 56 09](https://github.com/user-attachments/assets/19a23434-1b89-426c-9411-d25eb9e6874c)

#### Describe if there is any unusual behaviour of your code 

#### Additional context 

#### Test plan 

#### Checklist

- [ ] Refer to issue(s) the PR solves
- [ ] New java code is covered by tests
- [ ] Add screenshots or gifs of the new behavior, if applicable.
- [ ] All new and existing tests pass
- [ ] No git conflict

2024-12-30 16:54 UTC, nbrouand commented on chutney/server/src/main/java/com/chutneytesting/campaign/infra/index/CampaignIndexRepository.java
> +        luceneIndexRepository.update(byIdQuery(campaign.id().toString()), document);
we should also index scenario name in campaign

2024-12-30 16:54 UTC, nbrouand commented on chutney/server/src/main/java/com/chutneytesting/campaign/infra/index/CampaignIndexRepository.java
> +        luceneIndexRepository.update(byIdQuery(campaign.id().toString()), document);
and dataset used ?

2025-02-06 14:21 UTC, DelaunayAlex requested changes

2025-02-06 14:21 UTC, DelaunayAlex commented on chutney/ui/src/app/modules/campaign/campaign.routes.ts
> +        pathMatch: 'full'
Don't we need : "data: { 'authorizations': [ Authorization.CAMPAIGN_READ ] }" ?

2025-02-06 14:21 UTC, DelaunayAlex commented on chutney/ui/src/app/core/services/search.service.ts
> +import { catchError, debounceTime, distinctUntilChanged, map, Observable, of } from 'rxjs';
Clear unused

2025-02-06 14:21 UTC, DelaunayAlex commented on chutney/ui/src/app/core/model/search/hit.model.ts
> +                index = valueStr.indexOf(searchTerm, index + searchTerm.length);
Not used

2025-02-06 14:21 UTC, DelaunayAlex commented on chutney/ui/src/app/core/model/search/hit.model.ts
> +    search(searchTerm: string): { attribute: string; snippet: string }[] {
I prefer something like this with map and filter

```
search(searchTerm: string): { attribute: string; snippet: string }[] {
        return Object.entries(this)
            .map(([key, value]) => {
                let valueStr: string;
                if (typeof value === 'string') {
                    valueStr = value;
                } else if (value !== null && value !== undefined) {
                    valueStr = typeof value === 'object' ? JSON.stringify(value) : value.toString();
                } else {
                    return null;
                }
                return {key, valueStr}
            })
            .filter(res => res !== null)
            .map((res) => {
                let index = res.valueStr.indexOf(searchTerm);
                if (index !== -1) {
                    const start = Math.max(0, index - 40);
                    const end = Math.min(res.valueStr.length, index + searchTerm.length + 40);
                    return {
                        attribute: res.key,
                        snippet: res.valueStr.substring(start, end),
                    };
                }
                return null
            })
            .filter(res => res !== null)
    }

```

2025-02-06 17:33 UTC, boddissattva commented
My two cents on the new ui : 
* "no result" is too small. I prefer it for example with `mb-0 fs-6 fw-bold`
* The input search does not take all the width of the component. We could click on it without the focus on the input.
* The info tooltip on each line could have a border like `border border-info` for example because it blends too much with the search content result.
* When i scroll the search content result, i would like to have a `sticky` category header until the next one.

Not specific ui : 
* The multle words search does not work.
* Some special characters seem not to be indexed (like - and # for example). Check the stop words used.

2025-02-07 13:28 UTC, nbrouand commented on chutney/ui/src/app/modules/campaign/campaign.routes.ts
> +        pathMatch: 'full'
redirectTo and canActivate cannot be used together. Redirects happen before activation so canActivate will never be executed.

2025-02-18 13:48 UTC, DelaunayAlex commented on chutney/server/src/test/java/com/chutneytesting/index/domain/IndexRepositoryTest.java
> +        // Initialisation des repositories
French

2025-02-24 08:30 UTC, boddissattva approved these changes

2025-02-24 08:31 UTC, DelaunayAlex approved these changes

2025-02-24 08:32 UTC, merged